// Empty implementations of libultra internals that Body Harvest's recompiled
// code calls but the N64ModernRuntime doesn't provide. These are typically
// scheduler/interrupt/raw-I/O primitives whose work is handled at a higher
// level on PC (real OS threads instead of N64 cooperative scheduling, real
// PI DMA at librecomp's level, no VI interrupt model, etc.), so no-op
// implementations are safe.
//
// If anything actually depended on observable side effects from these (e.g.
// returning state via the recomp_context), this is the file to extend.
//
// Names and signatures must match the prototypes generated by
// gen_recomp_extras.py from the recompiled call sites.

#include "recomp.h"

extern "C" {

// Forward `func_8001BCE0_1C8E0` (BH's hand-coded osAiGetLength) to
// librecomp's working `osAiGetLength_recomp`, which reads our PC-side audio
// buffer state instead of N64 MMIO. Without this BH busy-spins forever
// thinking the audio buffer is always drained. (Marked `ignored` in
// bh.us.toml so N64Recomp does not emit a body for it.)
void osAiGetLength_recomp(uint8_t* rdram, recomp_context* ctx);  // librecomp
void func_8001BCE0_1C8E0(uint8_t* rdram, recomp_context* ctx) {
    osAiGetLength_recomp(rdram, ctx);
}

// BH's hand-coded `__osPiGetStatus`. Reads PI_STATUS_REG (0xA4600010) and
// returns it in $v0. On real N64 the PI status bits 0/1 indicate DMA busy /
// IO busy. On PC there is no PI hardware and our PI DMA is synchronous, so
// "always idle" (= 0) is the right answer — callers polling this in a loop
// just exit the loop on the first read. Marked `ignored` in bh.us.toml.
void func_8001F6E0_202E0(uint8_t* /*rdram*/, recomp_context* ctx) {
    ctx->r2 = 0;
}

// BH's hand-coded `osEepromLongRead` (asm/1E1A0.s). The real implementation
// loops `osEepromRead` 8 bytes at a time with a 15-ms timer between blocks,
// matching the on-cart EEPROM chip's serial-bus pacing. On PC there's no
// chip and the whole save buffer is in host RAM, so we can satisfy the
// entire request in a single `save_read`.
//
// We can't forward to librecomp's `osEepromLongRead_recomp` directly
// because it asserts `nbytes % 8 == 0`, and BH calls this with
// nbytes=0x1BD=445 (non-multiple of 8). Replicate the BH-style behaviour
// where the read rounds up to whole 8-byte EEPROM blocks — the extra
// bytes land in the caller's buffer past the requested end, matching
// real hardware's read-by-block granularity. The buffer is always
// large enough (BH allocates a fixed area, 0x1C0+ bytes, big enough to
// absorb the slack).
//
// Args (MIPS o32): a0 = mesg queue ptr (ignored — synchronous on PC),
//                  a1 = starting 8-byte EEPROM block index,
//                  a2 = N64 RDRAM destination buffer,
//                  a3 = byte count requested.
// Returns 0 in $v0 ("success") to match libultra's contract.
// librecomp's `save_read` is internal to its pi.cpp (no public header) —
// declare here matching the macro-expanded signature: RDRAM_ARG expands
// to `uint8_t* rdram, ` and PTR(void) expands to int32_t (the N64-side
// pointer as a 32-bit signed value).
extern "C++" void save_read(uint8_t* rdram, int32_t rdram_address, uint32_t offset, uint32_t count);
void func_8001D5A0_1E1A0(uint8_t* rdram, recomp_context* ctx) {
    uint8_t  eep_block_index = uint8_t(ctx->r5);
    int32_t  buffer          = int32_t(ctx->r6);
    int32_t  nbytes          = int32_t(ctx->r7);
    if (nbytes <= 0) {
        ctx->r2 = -1;  // BH returns -0x1 when nbytes is non-positive
        return;
    }
    // Round up to whole 8-byte blocks. Matches BH's loop-decrement-by-8
    // semantics (loops while nbytes > 0, reads one block per iteration).
    constexpr uint32_t kEepBlock = 8;
    uint32_t rounded = ((uint32_t(nbytes) + kEepBlock - 1) / kEepBlock) * kEepBlock;
    save_read(rdram, buffer, uint32_t(eep_block_index) * kEepBlock, rounded);
    ctx->r2 = 0;
}

// Threading helpers — ultramodern reimplements the thread scheduler using
// real OS threads, so the per-thread enqueue/pop machinery isn't needed.
void __osPopThread_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}
void __osEnqueueThread_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}

// PI / DMA primitives — librecomp services PI DMA at a higher abstraction
// (recomp::do_rom_read etc.), so these low-level setup/IO primitives don't
// need to do anything.
void osPiRawReadIo_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}
void __osPiCreateAccessQueue_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}

// VI internals — the modern renderer hooks at the swap-buffer level, not at
// the VI register / interrupt level.
void __osViGetCurrentContext_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}
void __osViSwapContext_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}

// Timer interrupt vector — ultramodern dispatches timer expiry directly to
// the registered callback, so the original interrupt path isn't reached.
void __osTimerInterrupt_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}

// Controller serial CRC — librecomp synthesizes controller protocol responses
// at a higher level so the per-byte CRC helper isn't used.
void __osContAddressCrc_recomp(uint8_t* /*rdram*/, recomp_context* /*ctx*/) {}

}
