// Body Harvest recompiled — Phase 3a "just link" entry point.
//
// Sole goal of this file: produce an .exe whose every symbol resolves. We
// don't care if it actually runs. Anything not strictly necessary for the
// linker is stubbed (renderer that always returns invalid, no RSP microcode,
// no audio, etc.). Future phases replace these stubs with real impls.

#include <algorithm>  // std::clamp for XInput stick scaling
#include <atomic>
#include <chrono>
#include <cmath>      // std::abs for stick deadzone
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <exception>
#include <filesystem>
#include <memory>
#include <thread>
#include <typeinfo>

// Win32 for window creation.
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <dbghelp.h>  // SymInitialize / SymFromAddr for SEH symbolisation
#include <Xinput.h>   // Phase 9: real controller input via XInput
#include <mmreg.h>    // Phase 11: real audio output via XAudio2
#include <xaudio2.h>
#include <wrl/client.h>

#include "bh_app.hpp"

// librecomp
#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"
#include "librecomp/overlays.hpp"

// ultramodern
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/error_handling.hpp"
#include "ultramodern/input.hpp"

// The recomp entrypoint is generated by N64Recomp and declared in funcs.h.
// Forward-declared here to avoid pulling 14k lines of generated decls.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// Phase 13: cheat-keybind side-channel (see bh-app/src/bh_cheats.cpp).
// We capture rdram from the recomp entrypoint wrapper so stub_poll_input
// can write to BH's cheatInputBuffer without borrowing a recomp_context.
namespace bh::cheats {
    void inject_z_if_r_pressed(uint8_t* rdram, uint16_t buttons_now);
    void start_overlay_thread();
    void poll_overlay_hotkey(uint8_t* rdram);
    void apply_noclip_movement(uint8_t* rdram, float stick_x, float stick_y);
    void apply_disable_shields_tick(uint8_t* rdram);
    void apply_water_override_tick(uint8_t* rdram);
    void apply_render_cull_bypass_tick(uint8_t* rdram);
    void apply_far_plane_override_tick(uint8_t* rdram);
    void apply_save_state_tick(uint8_t* rdram);
}

// Phase 16 multiplayer POC — see bh-app/src/bh_net.cpp.
namespace bh::net {
    bool init(uint16_t my_port, uint16_t peer_port);
    void tick(uint8_t* rdram);
    void set_enabled(bool on);
    bool enabled();
}
std::atomic<uint8_t*> g_recomp_rdram{nullptr};

// Wrapper around recomp_entrypoint that captures the rdram pointer so
// non-recomp host code (input thread, etc.) can poke into N64 RAM via
// the same byte-swap rules the recompiler uses. Registered as the
// GameEntry::entrypoint in place of the bare recomp_entrypoint.
extern "C" void bh_recomp_entrypoint_with_rdram_capture(uint8_t* rdram,
                                                        recomp_context* ctx) {
    g_recomp_rdram.store(rdram, std::memory_order_release);
    recomp_entrypoint(rdram, ctx);
}

// Recompiled aspMain (audio synthesizer ucode), defined in bh-rsp/aspMain.cpp
// at translation-unit scope (no namespace) and with default C++ linkage.
// Must be declared at namespace scope here too — putting it inside the
// anonymous namespace would give it internal linkage and the link would
// resolve to "no such symbol" at link time.
extern RspExitReason aspMain(uint8_t* rdram, uint32_t ucode_addr);

// Phase 11 diag: aspMain exit-path counters. Live at file scope (NOT
// inside the anonymous namespace) so the extern "C" callbacks below can
// see them, and so the recompiled aspMain.cpp can call those callbacks.
//  - patched_jr_count = times we exited because do_indirect_jump fell
//    through to the "rspboot exit" fallback (we used to crash here)
//  - natural_break_count = times aspMain hit a real MIPS `break 0`
//    instruction, which is the "ucode finished its work cleanly" path
// If patched dominates and natural is ~0, aspMain almost never finishes
// the synthesis loop, which would explain why every sample buffer is 0.
std::atomic<uint64_t> g_aspmain_patched_jr{0};
std::atomic<uint64_t> g_aspmain_natural_break{0};
std::atomic<uint32_t> g_aspmain_last_jr_target{0};

// Track every UNIQUE jr target that exited via the patched fallback. Small
// fixed-size set (32 entries is wildly enough) with linear scan — only
// touched from the SP Task Thread, but written via atomics so the
// heartbeat reader can dump it. This lets us learn all the missing
// indirect-branch targets in ONE run instead of seeding them one-by-one.
constexpr int kMaxAspmainJrTargets = 64;
std::atomic<uint32_t> g_aspmain_jr_targets[kMaxAspmainJrTargets]{};
std::atomic<uint32_t> g_aspmain_jr_target_count{0};

extern "C" void aspmain_dbg_count_unhandled_jr(uint32_t jt) {
    g_aspmain_patched_jr.fetch_add(1, std::memory_order_relaxed);
    g_aspmain_last_jr_target.store(jt, std::memory_order_relaxed);

    // Linear-scan-and-insert. Single-threaded caller (SP Task Thread),
    // but we use atomics so the heartbeat can read concurrently.
    uint32_t n = g_aspmain_jr_target_count.load(std::memory_order_relaxed);
    for (uint32_t i = 0; i < n && i < kMaxAspmainJrTargets; i++) {
        if (g_aspmain_jr_targets[i].load(std::memory_order_relaxed) == jt) {
            return;  // already recorded
        }
    }
    if (n < kMaxAspmainJrTargets) {
        g_aspmain_jr_targets[n].store(jt, std::memory_order_relaxed);
        g_aspmain_jr_target_count.store(n + 1, std::memory_order_relaxed);
    }
}
extern "C" void aspmain_dbg_count_natural_break(void) {
    g_aspmain_natural_break.fetch_add(1, std::memory_order_relaxed);
}

namespace {

// Diagnostic counters for Phase 3c — let us see at a glance whether the
// game thread is generating display lists, VI ticks are advancing, etc.
std::atomic<uint64_t> g_send_dl_count{0};
std::atomic<uint64_t> g_update_screen_count{0};
std::atomic<uint64_t> g_get_rsp_microcode_count{0};

// Audio simulator state (used by the stub audio callbacks further down,
// and by the heartbeat log).
std::atomic<uint64_t> g_audio_frames_queued{0};
std::atomic<uint64_t> g_audio_queue_calls{0};
std::atomic<uint64_t> g_audio_setfreq_calls{0};
std::atomic<uint32_t> g_audio_sample_rate{48000};
const std::chrono::steady_clock::time_point g_audio_t0 =
    std::chrono::steady_clock::now();

// Phase 6 deadlock instrumentation: track wall-clock time of the most
// recent significant event so the heartbeat can report "ms since last X".
// "ucode_in" is when get_rsp_microcode was called (a task is being
// dispatched); "ucode_out" is when our wrapper returned post-aspMain.
// If ucode_in is recent but ucode_out is old → we're stuck inside aspMain.
// If both are old but VI ticks → BH game thread isn't queuing new tasks.
std::atomic<int64_t> g_t_ucode_in_ns{0};
std::atomic<int64_t> g_t_ucode_out_ns{0};
std::atomic<int64_t> g_t_audio_queue_ns{0};
std::atomic<int64_t> g_t_audio_getlen_ns{0};
std::atomic<uint64_t> g_audio_getlen_calls{0};
std::atomic<int64_t> g_t_input_poll_ns{0};
std::atomic<uint64_t> g_input_poll_calls{0};

inline int64_t now_ns() {
    return std::chrono::duration_cast<std::chrono::nanoseconds>(
               std::chrono::steady_clock::now().time_since_epoch())
        .count();
}

// ---------------------------------------------------------------------------
// RSP microcode dispatch.
// ---------------------------------------------------------------------------
// Phase 5: real aspMain (audio synthesizer) lifted from BH's ROM by
// RSPRecomp into bh-rsp/aspMain.cpp. Audio task type 2 (M_AUDTASK)
// dispatches here; everything else still falls back to the no-op so the
// game's audio thread can drain its queue without bailing.

RspExitReason noop_rsp_ucode(uint8_t* /*rdram*/, uint32_t /*ucode_addr*/) {
    return RspExitReason::Broke;
}

// Per-task-type tally so we can tell whether BH is feeding only audio
// (type 2 = M_AUDTASK), gfx (type 1 = M_GFXTASK), or other tasks.
std::atomic<uint64_t> g_rsp_task_type_count[16]{};

// Wrap aspMain so we can timestamp before-and-after. If ucode_in is fresh
// but ucode_out is stale, the heartbeat tells us aspMain is stuck.
RspExitReason aspMain_traced(uint8_t* rdram, uint32_t ucode_addr) {
    g_t_ucode_in_ns.store(now_ns(), std::memory_order_relaxed);
    RspExitReason r = aspMain(rdram, ucode_addr);
    g_t_ucode_out_ns.store(now_ns(), std::memory_order_relaxed);
    return r;
}

RspUcodeFunc* stub_get_rsp_microcode(const OSTask* task) {
    g_get_rsp_microcode_count.fetch_add(1, std::memory_order_relaxed);
    if (task) {
        uint32_t t = task->t.type;
        if (t < 16) {
            g_rsp_task_type_count[t].fetch_add(1, std::memory_order_relaxed);
        }
        // M_AUDTASK == 2 in libultra. Route to the lifted aspMain so the
        // audio engine actually produces samples instead of dropping them.
        if (t == 2) {
            return aspMain_traced;
        }
    }
    return noop_rsp_ucode;
}

// ---------------------------------------------------------------------------
// Win32 window — minimal HWND so RT64 has a real swapchain target.
// ---------------------------------------------------------------------------
LRESULT CALLBACK bh_wndproc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp) {
    // Trace any "the window is going away" message so we can tell whether
    // the process is exiting because the window was destroyed (vs. the
    // game thread terminating cleanly).
    switch (msg) {
        case WM_CLOSE:
            std::fprintf(stderr, "[wnd] WM_CLOSE -> ultramodern::quit\n");
            ultramodern::quit();
            PostQuitMessage(0);
            return 0;
        case WM_DESTROY:
            std::fprintf(stderr, "[wnd] WM_DESTROY\n");
            break;
        case WM_QUIT:
            std::fprintf(stderr, "[wnd] WM_QUIT\n");
            break;
        case WM_QUERYENDSESSION:
            std::fprintf(stderr, "[wnd] WM_QUERYENDSESSION\n");
            break;
        case WM_ENDSESSION:
            std::fprintf(stderr, "[wnd] WM_ENDSESSION\n");
            break;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

HWND g_window = nullptr;
DWORD g_window_thread_id = 0;

void* gfx_create_gfx() { return nullptr; }

ultramodern::renderer::WindowHandle
gfx_create_window(ultramodern::gfx_callbacks_t::gfx_data_t /*gfx_data*/) {
    HINSTANCE hinst = GetModuleHandleW(nullptr);
    WNDCLASSW wc{};
    wc.lpfnWndProc = bh_wndproc;
    wc.hInstance = hinst;
    wc.hCursor = LoadCursorW(nullptr, MAKEINTRESOURCEW(32512)); // IDC_ARROW
    wc.lpszClassName = L"BHRecompWindow";
    RegisterClassW(&wc);

    g_window = CreateWindowExW(
        0, L"BHRecompWindow", L"Body Harvest (recomp - Phase 15a)",
        WS_OVERLAPPEDWINDOW,
        CW_USEDEFAULT, CW_USEDEFAULT, 640, 480,
        nullptr, nullptr, hinst, nullptr);
    if (!g_window) {
        std::fprintf(stderr, "[bh_app] CreateWindowExW failed: %lu\n", GetLastError());
        return ultramodern::renderer::WindowHandle{};
    }
    ShowWindow(g_window, SW_SHOWNORMAL);
    g_window_thread_id = GetCurrentThreadId();

    ultramodern::renderer::WindowHandle wh{};
    wh.window = g_window;
    wh.thread_id = g_window_thread_id;
    return wh;
}

// gfx_callbacks.update_gfx runs on the main thread inside recomp::start's
// loop. We pump the Win32 message queue here so the window stays responsive.
// Also log a heartbeat once per ~second so we can tell whether the loop
// is still being driven (vs. the process being torn down externally).
void gfx_update_gfx(void*) {
    MSG msg;
    while (PeekMessageW(&msg, nullptr, 0, 0, PM_REMOVE)) {
        TranslateMessage(&msg);
        DispatchMessageW(&msg);
    }
    static std::atomic<uint64_t> tick{0};
    uint64_t n = tick.fetch_add(1, std::memory_order_relaxed);
    // recomp::start sleeps 1ms between calls, so n=1000 ~= 1s
    // Heartbeat ~every ~1s of wall-time (main loop runs ~64 Hz on Windows
    // without timeBeginPeriod(1)).
    if ((n % 60) == 0) {
        // Convert each "last event" timestamp to "ms ago" — easier to scan
        // than raw monotonic ns. -1 means the event has never happened.
        int64_t now = now_ns();
        auto ms_ago = [now](int64_t t) -> int64_t {
            return t == 0 ? -1 : (now - t) / 1'000'000;
        };
        std::fprintf(stderr,
            "[loop] tick=%llu  send_dl=%llu update_screen=%llu rsp_ucode=%llu  tasks{gfx=%llu aud=%llu vid=%llu njpeg=%llu hvq=%llu other=%llu}  audio_cb{setfreq=%llu queue=%llu frames_q=%llu getlen=%llu}  ms_ago{ucode_in=%lld ucode_out=%lld aud_q=%lld aud_getlen=%lld input=%lld(n=%llu)}\n",
            static_cast<unsigned long long>(n / 1000),
            static_cast<unsigned long long>(s_send_dl_count.load()),
            static_cast<unsigned long long>(s_update_screen_count.load()),
            static_cast<unsigned long long>(g_get_rsp_microcode_count.load()),
            static_cast<unsigned long long>(g_rsp_task_type_count[1].load()),  // M_GFXTASK
            static_cast<unsigned long long>(g_rsp_task_type_count[2].load()),  // M_AUDTASK
            static_cast<unsigned long long>(g_rsp_task_type_count[3].load()),  // M_VIDTASK
            static_cast<unsigned long long>(g_rsp_task_type_count[4].load()),  // M_NJPEGTASK
            static_cast<unsigned long long>(g_rsp_task_type_count[6].load()),  // M_HVQTASK
            static_cast<unsigned long long>(g_rsp_task_type_count[0].load() + g_rsp_task_type_count[5].load() + g_rsp_task_type_count[7].load() + g_rsp_task_type_count[8].load() + g_rsp_task_type_count[9].load()),
            static_cast<unsigned long long>(g_audio_setfreq_calls.load()),
            static_cast<unsigned long long>(g_audio_queue_calls.load()),
            static_cast<unsigned long long>(g_audio_frames_queued.load()),
            static_cast<unsigned long long>(g_audio_getlen_calls.load()),
            static_cast<long long>(ms_ago(g_t_ucode_in_ns.load())),
            static_cast<long long>(ms_ago(g_t_ucode_out_ns.load())),
            static_cast<long long>(ms_ago(g_t_audio_queue_ns.load())),
            static_cast<long long>(ms_ago(g_t_audio_getlen_ns.load())),
            static_cast<long long>(ms_ago(g_t_input_poll_ns.load())),
            static_cast<unsigned long long>(g_input_poll_calls.load()));
        // Phase 11 diag: only print aspMain exit-path stats when something
        // unusual happens — patched-jr exits should be 0 in a healthy run.
        // (The counters are always maintained; the heartbeat just doesn't
        // spam them when everything's fine.)
        uint32_t jr_n = g_aspmain_jr_target_count.load(std::memory_order_relaxed);
        uint64_t patched = g_aspmain_patched_jr.load(std::memory_order_relaxed);
        if (patched != 0 || jr_n != 0) {
            std::fprintf(stderr,
                "[loop]   aspMain{patched_jr=%llu natural_brk=%llu unique_jr=%u last=0x%04X}\n",
                static_cast<unsigned long long>(patched),
                static_cast<unsigned long long>(g_aspmain_natural_break.load()),
                unsigned(jr_n),
                unsigned(g_aspmain_last_jr_target.load()));
            if (jr_n > 0) {
                std::fprintf(stderr, "[loop]   aspMain_jr_targets={");
                for (uint32_t i = 0; i < jr_n; i++) {
                    std::fprintf(stderr, "%s0x%04X",
                                 i == 0 ? "" : ",",
                                 unsigned(g_aspmain_jr_targets[i].load(std::memory_order_relaxed)));
                }
                std::fprintf(stderr, "}\n");
            }
        }
    }
    // Replace tick=N with seconds elapsed by using actual time
    static auto t0 = std::chrono::steady_clock::now();
    (void)t0;
}

// ---------------------------------------------------------------------------
// Error handling: print to stderr instead of opening a dialog. We're a
// console app for now; we'd rather get the error in our log than block on
// a popup the user has to click through.
// ---------------------------------------------------------------------------
void stderr_message_box(const char* msg) {
    std::fprintf(stderr, "[ultramodern error] %s\n", msg);
}

// ---------------------------------------------------------------------------
// Phase 11: real audio output via XAudio2.
//
// BH's audio thread runs at whatever sample rate the recompiled aspMain
// outputs (set via osAiSetFrequency; typically 22 050 / 31 968 / 44 100 Hz
// — usually 31 968 Hz for level music and SFX). Stereo S16 interleaved.
// On real hardware those samples go straight to AI -> DAC.
//
// We feed them to XAudio2 instead: one mastering voice on the system's
// default output, one source voice fed by `SubmitSourceBuffer`. The
// queued-buffer count is what BH's `osAiGetLength` query reads to pace
// itself, so we use XAudio2's actual `BuffersQueued` state to report drain
// (and fall back to the wall-clock simulator if XAudio2 isn't available,
// e.g. headless CI).
//
// XAudio2 owns its callback thread — it copies the bytes we hand it before
// SubmitSourceBuffer returns, so we don't need to keep our buffers alive.
// We allocate one heap copy per call and let XAudio2 free it when the
// buffer drains (via the XAUDIO2_BUFFER::pContext + our callback).
struct AudioBufferContext {
    int16_t* samples;
};

class XAudio2VoiceCallback : public IXAudio2VoiceCallback {
public:
    void STDMETHODCALLTYPE OnVoiceProcessingPassStart(UINT32) override {}
    void STDMETHODCALLTYPE OnVoiceProcessingPassEnd() override {}
    void STDMETHODCALLTYPE OnStreamEnd() override {}
    void STDMETHODCALLTYPE OnBufferStart(void*) override {}
    void STDMETHODCALLTYPE OnLoopEnd(void*) override {}
    void STDMETHODCALLTYPE OnVoiceError(void*, HRESULT) override {}
    void STDMETHODCALLTYPE OnBufferEnd(void* pContext) override {
        // XAudio2 calls us on its own thread once the buffer has been
        // consumed by the mixer; free the heap copy we made in queue_samples.
        auto* ctx = static_cast<AudioBufferContext*>(pContext);
        if (ctx) {
            delete[] ctx->samples;
            delete ctx;
        }
    }
};

struct XAudio2Audio {
    Microsoft::WRL::ComPtr<IXAudio2> xaudio;
    IXAudio2MasteringVoice*          mastering = nullptr;
    IXAudio2SourceVoice*             source    = nullptr;
    uint32_t                          rate      = 0;
    XAudio2VoiceCallback              callback;
    std::mutex                        mtx;  // serialise rate-changes vs. submit
    bool                              started = false;
    bool                              failed  = false;
};

XAudio2Audio g_audio;

// Build / rebuild the source voice for the given sample rate. Called from
// stub_set_frequency (BH's `osAiSetFrequency`).
void xaudio_set_rate_locked(uint32_t freq) {
    if (!g_audio.xaudio || g_audio.failed) return;
    if (g_audio.source != nullptr && g_audio.rate == freq) return;

    if (g_audio.source != nullptr) {
        g_audio.source->Stop(0);
        g_audio.source->FlushSourceBuffers();
        g_audio.source->DestroyVoice();
        g_audio.source = nullptr;
        g_audio.started = false;
    }

    WAVEFORMATEX wfx{};
    wfx.wFormatTag      = WAVE_FORMAT_PCM;
    wfx.nChannels       = 2;                      // BH is stereo
    wfx.nSamplesPerSec  = freq;
    wfx.wBitsPerSample  = 16;
    wfx.nBlockAlign     = wfx.nChannels * wfx.wBitsPerSample / 8;
    wfx.nAvgBytesPerSec = wfx.nSamplesPerSec * wfx.nBlockAlign;

    HRESULT hr = g_audio.xaudio->CreateSourceVoice(
        &g_audio.source, &wfx, 0, XAUDIO2_DEFAULT_FREQ_RATIO, &g_audio.callback);
    if (FAILED(hr)) {
        std::fprintf(stderr, "[audio] CreateSourceVoice(rate=%u) failed: 0x%lX\n",
                     freq, (long)hr);
        g_audio.failed = true;
        return;
    }
    g_audio.rate = freq;
}

void stub_queue_samples(int16_t* data, size_t sample_count) {
    g_audio_queue_calls.fetch_add(1, std::memory_order_relaxed);
    g_audio_frames_queued.fetch_add(sample_count / 2,
                                    std::memory_order_relaxed);
    g_t_audio_queue_ns.store(now_ns(), std::memory_order_relaxed);

    std::lock_guard lock{g_audio.mtx};
    if (g_audio.failed) return;
    if (g_audio.source == nullptr) {
        // BH's first queue_samples sometimes lands before set_frequency.
        // Boot the voice at the currently-cached rate (defaults to 48 kHz)
        // so we don't drop the very first samples.
        xaudio_set_rate_locked(g_audio_sample_rate.load(std::memory_order_relaxed));
        if (g_audio.failed || g_audio.source == nullptr) return;
    }

    // Copy samples into a heap buffer that lives until OnBufferEnd. BH's
    // sample buffers are recycled per AI tick, so we can't reference them
    // directly. sample_count is the total int16_t count (= 2 × frames for
    // stereo); BH always submits stereo per osAiSetNextBuffer.
    //
    // *Channel swap is required.* The MEM_H/MEM_W macros store halfwords
    // at `(addr ^ 2)` to compensate for the big-endian -> little-endian
    // address swizzle. The consequence is that within each 4-byte word
    // holding an interleaved {L, R} stereo sample pair, the L and R get
    // swapped in our RDRAM mmap. Reading them out in-order gives [R, L]
    // instead of [L, R] — so left audio plays on the right speaker and
    // vice versa, which on hardware where one channel is muted (very
    // common in BH menus / cutscenes) presents as full silence. Match
    // Zelda64Recomp's fix: read the sample pairs swapped on the way to
    // XAudio2.
    const size_t bytes = sample_count * sizeof(int16_t);
    auto* copy = new int16_t[sample_count];
    int32_t peak_raw = 0, peak_swapped = 0;
    for (size_t i = 0; i + 1 < sample_count; i += 2) {
        const int16_t r_raw = data[i + 0];
        const int16_t l_raw = data[i + 1];
        copy[i + 0] = l_raw;  // L  <-  RDRAM slot that holds L
        copy[i + 1] = r_raw;  // R  <-  RDRAM slot that holds R
        peak_raw     = std::max(peak_raw,     std::abs(int32_t(r_raw)));
        peak_swapped = std::max(peak_swapped, std::abs(int32_t(l_raw)));
    }
    // Phase 11 diag (cheap): one-shot log when audio first wakes up so
    // we can confirm aspMain is producing signal during a session. Keeps
    // the peak counters as locals for inspection from windbg but no
    // per-buffer log spam.
    (void)peak_swapped;
    static std::atomic<bool> heard_nonzero{false};
    if (peak_raw != 0 && !heard_nonzero.exchange(true, std::memory_order_relaxed)) {
        std::fprintf(stderr, "[audio] First non-silent buffer (peak=%d). aspMain is producing samples.\n",
                     peak_raw);
    }
    auto* ctx = new AudioBufferContext{copy};

    XAUDIO2_BUFFER buf{};
    buf.AudioBytes = static_cast<UINT32>(bytes);
    buf.pAudioData = reinterpret_cast<const BYTE*>(copy);
    buf.pContext   = ctx;
    HRESULT hr = g_audio.source->SubmitSourceBuffer(&buf);
    if (FAILED(hr)) {
        static std::atomic<int> err_count{0};
        if (err_count.fetch_add(1, std::memory_order_relaxed) < 4) {
            std::fprintf(stderr, "[audio] SubmitSourceBuffer failed: 0x%lX (bytes=%zu)\n",
                         (long)hr, bytes);
        }
        delete[] copy;
        delete ctx;
        return;
    }
    if (!g_audio.started) {
        HRESULT hs = g_audio.source->Start(0);
        if (FAILED(hs)) {
            std::fprintf(stderr, "[audio] Source Start() failed: 0x%lX\n", (long)hs);
        } else {
            std::fprintf(stderr, "[audio] Source voice started (rate=%u Hz, stereo S16).\n",
                         g_audio.rate);
        }
        g_audio.started = true;
    }
}

size_t stub_get_frames_remaining() {
    g_audio_getlen_calls.fetch_add(1, std::memory_order_relaxed);
    g_t_audio_getlen_ns.store(now_ns(), std::memory_order_relaxed);

    // Prefer XAudio2's actual queue depth — it's the ground truth and
    // accounts for whatever buffering the host introduces.
    if (g_audio.source != nullptr) {
        XAUDIO2_VOICE_STATE state{};
        g_audio.source->GetState(&state, XAUDIO2_VOICE_NOSAMPLESPLAYED);
        const uint64_t frames_queued =
            g_audio_frames_queued.load(std::memory_order_relaxed);
        XAUDIO2_VOICE_STATE state2{};
        g_audio.source->GetState(&state2);
        if (frames_queued >= state2.SamplesPlayed) {
            return static_cast<size_t>(frames_queued - state2.SamplesPlayed);
        }
        return 0;
    }

    // Fallback: wall-clock simulator (used if XAudio2 init failed).
    auto now = std::chrono::steady_clock::now();
    uint64_t elapsed_ns =
        std::chrono::duration_cast<std::chrono::nanoseconds>(now - g_audio_t0)
            .count();
    uint64_t rate = g_audio_sample_rate.load(std::memory_order_relaxed);
    uint64_t frames_played = (elapsed_ns * rate) / 1'000'000'000ULL;
    uint64_t frames_queued = g_audio_frames_queued.load(std::memory_order_relaxed);
    return frames_played >= frames_queued ? 0
                                           : static_cast<size_t>(frames_queued - frames_played);
}

void stub_set_frequency(uint32_t freq) {
    g_audio_setfreq_calls.fetch_add(1, std::memory_order_relaxed);
    if (freq == 0) return;
    g_audio_sample_rate.store(freq, std::memory_order_relaxed);

    std::lock_guard lock{g_audio.mtx};
    xaudio_set_rate_locked(freq);
}

// ---------------------------------------------------------------------------
// XInput plumbing — wire Xbox-style controllers to BH's N64 OSContPad.
//
// Polled from stub_poll_input (called once per osContStartReadData, which
// after Phase 7's SI deferral runs at ~60 Hz). The N64-side stub_get_input
// then reads from the cached snapshot — keeps the conversion math out of
// any hot loop and matches real libultra semantics (one snapshot per
// joybus poll).
//
// N64 controller button bits (per libultra OSContPad.button):
//   0x8000 A      0x4000 B      0x2000 Z      0x1000 START
//   0x0800 D-Up   0x0400 D-Dn   0x0200 D-L    0x0100 D-R
//   0x0020 L      0x0010 R
//   0x0008 C-Up   0x0004 C-Dn   0x0002 C-L    0x0001 C-R
//
// Mapping (BH plays best with the standard N64-on-Xbox layout):
//   Xbox A          -> N64 A         (jump / confirm)
//   Xbox B          -> N64 B         (cancel / weapon swap)
//   Xbox X          -> N64 R         (alt grip; BH uses R rarely)
//   Xbox Y          -> N64 L
//   Xbox LB         -> N64 L
//   Xbox RB         -> N64 R
//   Xbox LT (>30%)  -> N64 Z         (shoot)
//   Xbox RT (>30%)  -> N64 Z         (shoot, either trigger)
//   Xbox D-Pad      -> N64 D-Pad
//   Xbox Start      -> N64 START
//   Xbox Back       -> N64 START     (no good N64 equivalent)
//   Xbox L stick    -> N64 analog stick (drive / walk)
//   Xbox R stick    -> N64 C buttons (look / aim, thresholded at >40%)
struct ControllerSnapshot {
    uint16_t buttons = 0;
    float    stick_x = 0.0f;
    float    stick_y = 0.0f;
    bool     connected = false;
};
std::atomic<bool> g_xinput_warned_missing{false};
// Lock-free per-controller snapshot: each controller has its own
// 64-bit slot, packed as { buttons:16, x_q15:16, y_q15:16, connected:1 }.
// 64-bit aligned atomic writes are atomic on x86-64, so reader sees a
// coherent snapshot without taking a lock.
std::atomic<uint64_t> g_pad_snapshots[4]{};

inline uint64_t pack_snapshot(const ControllerSnapshot& s) {
    auto qx = static_cast<int16_t>(std::clamp(s.stick_x, -1.0f, 1.0f) * 32767.0f);
    auto qy = static_cast<int16_t>(std::clamp(s.stick_y, -1.0f, 1.0f) * 32767.0f);
    return (uint64_t(s.buttons)     <<  0)
         | (uint64_t(uint16_t(qx))  << 16)
         | (uint64_t(uint16_t(qy))  << 32)
         | (uint64_t(s.connected ? 1u : 0u) << 48);
}

inline ControllerSnapshot unpack_snapshot(uint64_t v) {
    ControllerSnapshot s;
    s.buttons   = uint16_t(v & 0xFFFF);
    s.stick_x   = float(int16_t((v >> 16) & 0xFFFF)) / 32767.0f;
    s.stick_y   = float(int16_t((v >> 32) & 0xFFFF)) / 32767.0f;
    s.connected = ((v >> 48) & 1u) != 0;
    return s;
}

// Convert one XINPUT_STATE.Gamepad to our snapshot.
ControllerSnapshot translate_xinput(const XINPUT_GAMEPAD& gp) {
    ControllerSnapshot s{};
    s.connected = true;

    // ---- Face / shoulder / start buttons ----
    if (gp.wButtons & XINPUT_GAMEPAD_A)              s.buttons |= 0x8000;          // A
    if (gp.wButtons & XINPUT_GAMEPAD_B)              s.buttons |= 0x4000;          // B
    if (gp.wButtons & XINPUT_GAMEPAD_X)              s.buttons |= 0x0010;          // R (alt)
    if (gp.wButtons & XINPUT_GAMEPAD_Y)              s.buttons |= 0x0020;          // L (alt)
    if (gp.wButtons & XINPUT_GAMEPAD_LEFT_SHOULDER)  s.buttons |= 0x0020;          // L
    if (gp.wButtons & XINPUT_GAMEPAD_RIGHT_SHOULDER) s.buttons |= 0x0010;          // R
    if (gp.wButtons & XINPUT_GAMEPAD_START)          s.buttons |= 0x1000;          // START
    if (gp.wButtons & XINPUT_GAMEPAD_BACK)           s.buttons |= 0x1000;          // START (fallback)

    // Triggers (XInput trigger range 0..255) -> Z if past 30%
    constexpr uint8_t kTriggerThreshold = 256 * 30 / 100;
    if (gp.bLeftTrigger  > kTriggerThreshold) s.buttons |= 0x2000;                  // Z
    if (gp.bRightTrigger > kTriggerThreshold) s.buttons |= 0x2000;                  // Z

    // ---- D-Pad ----
    if (gp.wButtons & XINPUT_GAMEPAD_DPAD_UP)    s.buttons |= 0x0800;
    if (gp.wButtons & XINPUT_GAMEPAD_DPAD_DOWN)  s.buttons |= 0x0400;
    if (gp.wButtons & XINPUT_GAMEPAD_DPAD_LEFT)  s.buttons |= 0x0200;
    if (gp.wButtons & XINPUT_GAMEPAD_DPAD_RIGHT) s.buttons |= 0x0100;

    // ---- Left stick (analog) ----
    // XInput stick range: int16 -32768..32767. Dead-zone using the
    // documented threshold so resting controllers don't drift.
    auto apply_dz = [](int16_t v, int dz) -> float {
        int av = std::abs(int(v));
        if (av < dz) return 0.0f;
        float sign = v < 0 ? -1.0f : 1.0f;
        return sign * float(av - dz) / float(32767 - dz);
    };
    s.stick_x = apply_dz(gp.sThumbLX, XINPUT_GAMEPAD_LEFT_THUMB_DEADZONE);
    s.stick_y = apply_dz(gp.sThumbLY, XINPUT_GAMEPAD_LEFT_THUMB_DEADZONE);

    // ---- Right stick -> C buttons ----
    // Threshold at ~40% past dead-zone for a click-y feel; BH only cares
    // whether the C button is down, not how far.
    const float c_threshold = 0.4f;
    float rx = apply_dz(gp.sThumbRX, XINPUT_GAMEPAD_RIGHT_THUMB_DEADZONE);
    float ry = apply_dz(gp.sThumbRY, XINPUT_GAMEPAD_RIGHT_THUMB_DEADZONE);
    if (ry >  c_threshold) s.buttons |= 0x0008;  // C-Up
    if (ry < -c_threshold) s.buttons |= 0x0004;  // C-Down
    if (rx < -c_threshold) s.buttons |= 0x0002;  // C-Left
    if (rx >  c_threshold) s.buttons |= 0x0001;  // C-Right

    return s;
}

void stub_poll_input() {
    g_input_poll_calls.fetch_add(1, std::memory_order_relaxed);
    g_t_input_poll_ns.store(now_ns(), std::memory_order_relaxed);

    // Poll all four XInput slots. BH's max_controllers is set by osContSetCh
    // (usually 1 for single-player), but ultramodern still asks via
    // get_connected_device_info for higher slots — keep them all live.
    bool any_connected = false;
    for (int i = 0; i < 4; i++) {
        XINPUT_STATE state{};
        DWORD r = XInputGetState(DWORD(i), &state);
        if (r == ERROR_SUCCESS) {
            any_connected = true;
            g_pad_snapshots[i].store(pack_snapshot(translate_xinput(state.Gamepad)),
                                      std::memory_order_release);
        } else {
            g_pad_snapshots[i].store(0, std::memory_order_release);
        }
    }
    if (!any_connected && !g_xinput_warned_missing.exchange(true, std::memory_order_relaxed)) {
        std::fprintf(stderr,
            "[input] No XInput controllers connected. Plug in a controller "
            "(Xbox / DS4-via-DS4Windows / 8BitDo / etc.) and BH will see it "
            "without a restart.\n");
    }

    // Phase 13: cheat-keybind side-channel. Looks at player 1's current
    // buttons and, on a fresh R-trigger press, writes a 'z' into BH's
    // cheatInputBuffer (gated on isCheatingEnabled, which BH already
    // requires the player to unlock via a save slot named "ICHEAT").
    // This restores the six z-prefixed cheats (zfarewell, zwander,
    // zaward, zsnared, zfreed, zdefender) that ship with the game but
    // were locked out by the lack of a 'z' button binding. R is chosen
    // over L because L pops up the in-game objective screen, which
    // would swallow any follow-up button presses needed to type the
    // rest of the cheat name.
    uint8_t* rdram = g_recomp_rdram.load(std::memory_order_acquire);
    auto snap = unpack_snapshot(g_pad_snapshots[0].load(std::memory_order_acquire));
    bh::cheats::inject_z_if_r_pressed(rdram, snap.buttons);

    // Phase 14: F1 toggles the cheat-overlay window (always available,
    // bypasses BH's isCheatingEnabled gate). Detection lives here so
    // we share the input-poll cadence; the actual window runs on its
    // own thread started below in main().
    bh::cheats::poll_overlay_hotkey(rdram);

    // Phase 14c: noclip movement override. Runs every poll tick when
    // the menu toggle is on; no-op otherwise. Stick is player 1's
    // analog stick from the same snapshot we just read.
    bh::cheats::apply_noclip_movement(rdram, snap.stick_x, snap.stick_y);

    // Re-apply shield-wall disable each tick. BH restores the shield
    // wall source table from ROM on building entry/exit and level
    // transitions, so a one-shot patch would silently revert. The
    // function early-outs cheaply if the disable flag isn't set.
    bh::cheats::apply_disable_shields_tick(rdram);

    // Re-apply water-level override each tick. Per-level scripts
    // (Java boss arena lowers water on boss spawn, etc.) stomp the
    // global water Y; without the tick the user's slider value or
    // "drain water" cheat would get reset on state changes.
    bh::cheats::apply_water_override_tick(rdram);

    // Per-tick render-cull bypass — when on, writes D_8014FD2A to
    // BH's "render everything" sentinel so the master cull function
    // returns "render" for all entities. No-op when the toggle is off.
    bh::cheats::apply_render_cull_bypass_tick(rdram);

    // Per-tick far-plane override — extends the GPU Z-clip distance
    // by writing a scaled multiple of the BH-original far plane to
    // D_801411A4 each input poll. No-op when the slider's at 1.0x or
    // explicitly released.
    bh::cheats::apply_far_plane_override_tick(rdram);

    // Save-state I/O — when the "Save State" / "Load State" cheats
    // queue an operation, this handler performs the disk I/O here
    // at the frame boundary (between BH game ticks). Single-shot
    // per cheat fire; no-op the rest of the time.
    bh::cheats::apply_save_state_tick(rdram);

    // Phase 16: multiplayer POC tick — sends our position, drains
    // incoming packets, paints the ghost slot for the remote player.
    // No-op when the Options-tab toggle is off.
    bh::net::tick(rdram);
}

bool stub_get_input(int controller, uint16_t* buttons, float* x, float* y) {
    if (controller < 0 || controller >= 4) {
        if (buttons) *buttons = 0;
        if (x) *x = 0.0f;
        if (y) *y = 0.0f;
        return false;
    }
    auto snap = unpack_snapshot(g_pad_snapshots[controller].load(std::memory_order_acquire));
    if (buttons) *buttons = snap.buttons;
    if (x) *x = snap.stick_x;
    if (y) *y = snap.stick_y;
    return snap.connected;
}

void stub_set_rumble(int controller, bool on) {
    if (controller < 0 || controller >= 4) return;
    XINPUT_VIBRATION vib{};
    // Rumble Pak is a single-magnitude binary effect; mirror that with
    // both motors at full when on, both off when off.
    vib.wLeftMotorSpeed  = on ? 0xFFFF : 0;
    vib.wRightMotorSpeed = on ? 0xFFFF : 0;
    XInputSetState(DWORD(controller), &vib);
}

ultramodern::input::connected_device_info_t stub_get_connected_device_info(int controller) {
    if (controller < 0 || controller >= 4) {
        return { ultramodern::input::Device::None, ultramodern::input::Pak::None };
    }
    // BH calls osContInit (which calls get_connected_device_info) BEFORE
    // its first osContStartReadData, so the snapshot polled in
    // stub_poll_input hasn't been written yet on the very first probe and
    // we'd incorrectly report "no controller connected". Refresh the
    // snapshot here so the probe sees current device state. Subsequent
    // poll cycles will keep it updated.
    XINPUT_STATE state{};
    if (XInputGetState(DWORD(controller), &state) == ERROR_SUCCESS) {
        g_pad_snapshots[controller].store(pack_snapshot(translate_xinput(state.Gamepad)),
                                          std::memory_order_release);
        return { ultramodern::input::Device::Controller,
                 ultramodern::input::Pak::RumblePak };
    }
    g_pad_snapshots[controller].store(0, std::memory_order_release);
    return { ultramodern::input::Device::None, ultramodern::input::Pak::None };
}

} // namespace

int main(int argc, char** argv) {
    // Make stdout/stderr unbuffered so log lines flush immediately even when
    // the process is killed mid-bootstrap (very useful during phase 3b/3c).
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    std::setvbuf(stderr, nullptr, _IONBF, 0);

    // Initialise dbghelp's symbol engine once, here, so the SEH filter can
    // resolve the faulting RIP to a function name. With /Z7 + /DEBUG the
    // .pdb sits next to the exe; SymInitialize picks it up automatically.
    SymSetOptions(SYMOPT_LOAD_LINES | SYMOPT_UNDNAME);
    SymInitialize(GetCurrentProcess(), nullptr, /*invade*/ TRUE);

    // Phase 16: parse multiplayer port args. Defaults make two
    // instances on one PC just work — first instance uses defaults
    // (listen 12345 -> send 12346), second instance launched with
    //   bh_app.exe --port 12346 --peer-port 12345
    uint16_t mp_my_port = 12345, mp_peer_port = 12346;
    for (int i = 1; i + 1 < argc; ++i) {
        if (std::strcmp(argv[i], "--port") == 0) {
            mp_my_port = uint16_t(std::atoi(argv[++i]));
        } else if (std::strcmp(argv[i], "--peer-port") == 0) {
            mp_peer_port = uint16_t(std::atoi(argv[++i]));
        }
    }
    bh::net::init(mp_my_port, mp_peer_port);

    // Phase 11: bring up XAudio2 for real audio output. We don't yet know
    // the sample rate (BH calls osAiSetFrequency later); the source voice
    // is created on the first set_frequency or first queue_samples call.
    // If initialisation fails, stub_queue_samples falls back to drop-on-
    // floor + simulated drain via wall-clock, matching pre-Phase-11
    // behaviour so the rest of the runtime still works.
    HRESULT hr_audio = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
    if (SUCCEEDED(hr_audio) || hr_audio == RPC_E_CHANGED_MODE) {
        IXAudio2* raw_xaudio = nullptr;
        HRESULT hr = XAudio2Create(&raw_xaudio, 0, XAUDIO2_DEFAULT_PROCESSOR);
        if (SUCCEEDED(hr)) {
            g_audio.xaudio.Attach(raw_xaudio);
            hr = g_audio.xaudio->CreateMasteringVoice(&g_audio.mastering);
            if (FAILED(hr)) {
                std::fprintf(stderr, "[audio] CreateMasteringVoice failed: 0x%lX — falling back to silent simulator\n",
                             (long)hr);
                g_audio.xaudio.Reset();
                g_audio.failed = true;
            } else {
                std::fprintf(stderr, "[audio] XAudio2 initialised; awaiting BH's osAiSetFrequency.\n");
            }
        } else {
            std::fprintf(stderr, "[audio] XAudio2Create failed: 0x%lX — falling back to silent simulator\n",
                         (long)hr);
            g_audio.failed = true;
        }
    } else {
        std::fprintf(stderr, "[audio] CoInitializeEx failed: 0x%lX — falling back to silent simulator\n",
                     (long)hr_audio);
        g_audio.failed = true;
    }

    // Catch unhandled SEH (Windows structured exceptions like AV, divide
    // by zero, etc.) — these don't propagate through C++ try/catch or
    // std::terminate. The filter fires before WER takes over so we still
    // get a chance to log the faulting address.
    SetUnhandledExceptionFilter([](EXCEPTION_POINTERS* ep) -> LONG {
        DWORD code = ep->ExceptionRecord->ExceptionCode;
        void* pc = ep->ExceptionRecord->ExceptionAddress;
        std::fprintf(stderr, "\n[SEH] Unhandled exception 0x%08lX at %p\n",
                     code, pc);

        // Symbolise the faulting RIP. SymFromAddr writes a SYMBOL_INFO with
        // the function name + offset within it. We also try SymGetLineFromAddr64
        // for file:line if line info was emitted (it was, via /Z7).
        {
            constexpr size_t kMaxNameLen = 512;
            char buf[sizeof(SYMBOL_INFO) + kMaxNameLen];
            auto* sym = reinterpret_cast<SYMBOL_INFO*>(buf);
            sym->SizeOfStruct = sizeof(SYMBOL_INFO);
            sym->MaxNameLen = kMaxNameLen;
            DWORD64 disp = 0;
            if (SymFromAddr(GetCurrentProcess(),
                            reinterpret_cast<DWORD64>(pc), &disp, sym)) {
                std::fprintf(stderr, "[SEH]   in %s+0x%llX\n",
                             sym->Name, (unsigned long long)disp);
            }
            IMAGEHLP_LINE64 line{};
            line.SizeOfStruct = sizeof(line);
            DWORD line_disp = 0;
            if (SymGetLineFromAddr64(GetCurrentProcess(),
                                     reinterpret_cast<DWORD64>(pc),
                                     &line_disp, &line)) {
                std::fprintf(stderr, "[SEH]   at %s:%lu\n",
                             line.FileName, line.LineNumber);
            }
        }
        if (code == EXCEPTION_ACCESS_VIOLATION &&
            ep->ExceptionRecord->NumberParameters >= 2) {
            ULONG_PTR rw = ep->ExceptionRecord->ExceptionInformation[0];
            ULONG_PTR target = ep->ExceptionRecord->ExceptionInformation[1];
            std::fprintf(stderr, "[SEH]   AV %s 0x%p\n",
                         rw == 0 ? "read" :
                         rw == 1 ? "write" : "exec",
                         (void*)target);
        }
        std::fprintf(stderr, "[SEH] rip=%p rax=%p rbx=%p rcx=%p rdx=%p\n",
                     (void*)ep->ContextRecord->Rip,
                     (void*)ep->ContextRecord->Rax,
                     (void*)ep->ContextRecord->Rbx,
                     (void*)ep->ContextRecord->Rcx,
                     (void*)ep->ContextRecord->Rdx);
        std::fprintf(stderr, "[SEH] rsi=%p rdi=%p r8 =%p r9 =%p r10=%p\n",
                     (void*)ep->ContextRecord->Rsi,
                     (void*)ep->ContextRecord->Rdi,
                     (void*)ep->ContextRecord->R8,
                     (void*)ep->ContextRecord->R9,
                     (void*)ep->ContextRecord->R10);
        std::fprintf(stderr, "[SEH] r11=%p r12=%p r13=%p r14=%p r15=%p rsp=%p\n",
                     (void*)ep->ContextRecord->R11,
                     (void*)ep->ContextRecord->R12,
                     (void*)ep->ContextRecord->R13,
                     (void*)ep->ContextRecord->R14,
                     (void*)ep->ContextRecord->R15,
                     (void*)ep->ContextRecord->Rsp);
        std::fflush(stderr);
        return EXCEPTION_EXECUTE_HANDLER;  // terminate the process ourselves
    });

    // Catch unhandled exceptions from any thread (including detached game,
    // bootstrap, gfx, etc.) and dump their type + message before the
    // process dies. Without this, std::terminate exits silently.
    std::set_terminate([]() {
        std::fprintf(stderr, "\n[bh_app] TERMINATE called\n");
        try {
            if (auto e = std::current_exception()) {
                std::rethrow_exception(e);
            } else {
                std::fprintf(stderr, "[bh_app] terminate with no current exception\n");
            }
        } catch (const std::exception& e) {
            std::fprintf(stderr, "[bh_app]   type:    %s\n", typeid(e).name());
            std::fprintf(stderr, "[bh_app]   what():  %s\n", e.what());
        } catch (...) {
            std::fprintf(stderr, "[bh_app]   unknown non-std exception\n");
        }
        std::fflush(stderr);
        std::abort();
    });

    std::printf("bh_app: Body Harvest recompiled (Phase 4b)\n");
    std::fprintf(stderr, "[trace] before register_overlays\n");

    // Tell librecomp about all of Body Harvest's recompiled functions before
    // any of them have a chance to run.
    bh::register_overlays();
    std::fprintf(stderr, "[trace] after register_overlays\n");

    // Describe BH as a registered game. ROM hash is XXH3_64bits of the
    // 12 MiB baserom.us.z64 padded to a multiple of 4 bytes (computed once
    // via hash_rom.cpp). Mismatched bytes here would cause select_rom to
    // return IncorrectRom.
    recomp::GameEntry bh_entry{};
    bh_entry.rom_hash          = 0x9949AA9BC66F33CBULL;
    bh_entry.internal_name     = "BODY HARVEST";
    bh_entry.game_id           = u8"bh.n64.us";
    bh_entry.mod_game_id       = "bh";
    // BH's libultra code uses EEPROM (osEepromProbe / osEepromLongWrite /
    // osEepromLongRead — see src.us/core/1050.c). Each long write is
    // 0x1BD = 445 bytes, which fits 4kbit EEPROM (512 bytes) with room
    // to spare; no 16kbit needed. Registering as Sram here causes our
    // osEepromProbe_recomp to return 0 (no EEPROM detected), BH's
    // D_80047608 stays 0, and BH skips every subsequent EEPROM call
    // (read AND write) — i.e. saves silently never persist.
    bh_entry.save_type         = recomp::SaveType::Eep4k;
    bh_entry.is_enabled        = true;
    bh_entry.entrypoint_address = get_entrypoint_address();
    // Phase 13: use the rdram-capturing wrapper so the cheat side-channel
    // (and any future host-side hook) can reach into N64 RAM by symbol.
    bh_entry.entrypoint        = bh_recomp_entrypoint_with_rdram_capture;
    std::fprintf(stderr, "[trace] before register_game\n");
    recomp::register_game(bh_entry);
    std::fprintf(stderr, "[trace] after register_game\n");

    // Phase 14: spin up the Win32 cheats-overlay window on its own
    // thread so F1 can toggle it independently of the game thread.
    bh::cheats::start_overlay_thread();

    // librecomp needs a config dir to stash the validated ROM under and to
    // create `mods/` and `mod_config/` subdirs in. Pin it to the directory
    // the exe lives in — `current_path()` is unreliable (when launched
    // under windbg the cwd is `C:\WINDOWS\system32`, which throws "Access
    // is denied" the moment librecomp tries to mkdir under it).
    // Phase 6 should switch to a proper per-user path (SHGetKnownFolderPath
    // for FOLDERID_LocalAppData on Windows).
    wchar_t exe_path_buf[MAX_PATH] = {};
    GetModuleFileNameW(nullptr, exe_path_buf, MAX_PATH);
    std::filesystem::path config_dir =
        std::filesystem::path(exe_path_buf).parent_path() / "config";
    std::filesystem::create_directories(config_dir);
    recomp::register_config_path(config_dir);
    std::fprintf(stderr, "[trace] after register_config_path\n");

    // Build a Configuration with stub callbacks. Mandatory ones are filled,
    // optional ones are left default-constructed (nullptr fn pointers).
    recomp::Configuration cfg{};
    cfg.project_version = recomp::Version{0, 1, 0, "-phase15a"};

    cfg.rsp_callbacks.get_rsp_microcode  = stub_get_rsp_microcode;
    cfg.renderer_callbacks.create_render_context = bh::create_render_context;

    cfg.gfx_callbacks.create_gfx    = gfx_create_gfx;
    cfg.gfx_callbacks.create_window = gfx_create_window;
    cfg.gfx_callbacks.update_gfx    = gfx_update_gfx;

    cfg.error_handling_callbacks.message_box = stderr_message_box;

    cfg.audio_callbacks.queue_samples        = stub_queue_samples;
    cfg.audio_callbacks.get_frames_remaining = stub_get_frames_remaining;
    cfg.audio_callbacks.set_frequency        = stub_set_frequency;

    cfg.input_callbacks.poll_input               = stub_poll_input;
    cfg.input_callbacks.get_input                = stub_get_input;
    cfg.input_callbacks.set_rumble               = stub_set_rumble;
    cfg.input_callbacks.get_connected_device_info = stub_get_connected_device_info;

    // (Watchdog disabled while we isolate the post-Phase-4a regression.)

    // recomp::start blocks forever pumping update_gfx. We need a sidecar
    // thread to kick off the game once ultramodern is ready. The sidecar
    // sleeps briefly to let start_event_threads finish, validates the ROM
    // via select_rom (which copies it to config_path and verifies the hash),
    // and then flips game_status to Running.
    std::thread bootstrap_thread([]() {
        std::this_thread::sleep_for(std::chrono::milliseconds(250));

        const std::filesystem::path rom_path =
            R"(C:\BodyHarvestPC\body-harvest-decompilation\baserom.us.z64)";
        std::u8string game_id = u8"bh.n64.us";

        auto err = recomp::select_rom(rom_path, game_id);
        if (err != recomp::RomValidationError::Good) {
            std::fprintf(stderr, "[bh_app] select_rom failed: %d\n",
                         static_cast<int>(err));
            return;
        }
        std::fprintf(stderr, "[bh_app] ROM validated; starting game\n");
        recomp::start_game(game_id);
    });
    bootstrap_thread.detach();

    std::fprintf(stderr, "[trace] before recomp::start\n");
    // start() is supposed to never return under normal operation.
    try {
        recomp::start(cfg);
    } catch (const std::exception& e) {
        std::fprintf(stderr,
            "\n[bh_app] recomp::start threw: %s: %s\n",
            typeid(e).name(), e.what());
        std::fflush(stderr);
        return 1;
    } catch (...) {
        std::fprintf(stderr, "\n[bh_app] recomp::start threw unknown exception\n");
        std::fflush(stderr);
        return 1;
    }
    std::fprintf(stderr, "[trace] after recomp::start (unexpected)\n");

    std::printf("bh_app: recomp::start returned (unexpected for now)\n");
    return 0;
}
