// Public surface of bh_app_glue. Anything the main entry point or future
// game/runtime hooks needs to call lives here.

#pragma once

#include <atomic>
#include <cstdint>
#include <memory>

#include "recomp.h"  // for gpr
#include "ultramodern/renderer_context.hpp"

// Diagnostic counters incremented by bh_renderer.cpp.
extern std::atomic<uint64_t> s_send_dl_count;
extern std::atomic<uint64_t> s_update_screen_count;

namespace bh {
    // Registers all recompiled function tables (sections + overlays) with
    // librecomp. Call once at startup before any recompiled code runs.
    void register_overlays();

    // RT64-backed RendererContext factory. Plug into
    // recomp::Configuration::renderer_callbacks.create_render_context.
    std::unique_ptr<ultramodern::renderer::RendererContext>
    create_render_context(uint8_t* rdram,
                          ultramodern::renderer::WindowHandle window_handle,
                          bool developer_mode);
}

// Provided by RecompiledFuncs/lookup.cpp (auto-generated by N64Recomp).
// Declared here so callers in this project can pick up the prototypes.
// Note: lookup.cpp emits these as plain C++ functions (no extern "C"), so
// keep the declarations consistent.
gpr get_entrypoint_address();
const char* get_rom_name();
