#!/usr/bin/env python3
"""Scan the RecompiledFuncs output for `*_recomp` calls and emit forward
declarations for any not already declared in funcs.h.

N64Recomp renames calls to "reimplemented" libultra functions to their
`*_recomp` form but only writes prototypes for functions whose bodies it
actually compiled. The runtime (librecomp) implements the rest as
`extern "C"` C++ functions with no header. Without the prototypes below,
strict C compilers (e.g. clang-cl) error with
`implicit-function-declaration`.

Run this at CMake-configure time. Output goes to a header that the build
prepends to every recompiled .c via `/FI`.
"""

import re
import sys
from pathlib import Path


_NAME = r"[A-Za-z_][A-Za-z0-9_]*"

# Calls we care about: anything that LOOKS like a recomp function call —
# either the librecomp-provided `*_recomp` style or a BH-style
# `func_XXXXXXXX_YYYYY` style. The second pattern catches functions that
# we've marked `[patches] ignored` (no body emitted) but that other
# recompiled functions still call.
CALL_RE = re.compile(
    rf"\b({_NAME}_recomp|func_[0-9A-Fa-f]+(?:_[0-9A-Fa-f]+)?)\s*\("
)

DECL_RE = re.compile(rf"\bvoid\s+({_NAME})\s*\(")


def main(funcs_dir: str, out_path: str) -> int:
    funcs_dir_p = Path(funcs_dir)
    if not funcs_dir_p.is_dir():
        print(f"Not a directory: {funcs_dir}", file=sys.stderr)
        return 1

    funcs_h = funcs_dir_p / "funcs.h"
    if not funcs_h.is_file():
        print(f"funcs.h missing: {funcs_h}", file=sys.stderr)
        return 1

    declared = set(DECL_RE.findall(funcs_h.read_text(encoding="utf-8", errors="ignore")))

    called: set[str] = set()
    for c_file in sorted(funcs_dir_p.glob("*.c")):
        text = c_file.read_text(encoding="utf-8", errors="ignore")
        called.update(CALL_RE.findall(text))

    missing = sorted(called - declared)
    out_p = Path(out_path)
    out_p.parent.mkdir(parents=True, exist_ok=True)
    with out_p.open("w", encoding="utf-8") as f:
        f.write("/* Auto-generated by gen_recomp_extras.py. Do not edit by hand.\n")
        f.write(" * Forward declarations for `*_recomp` functions whose bodies are\n")
        f.write(" * implemented in librecomp (or other runtime libs) but for which\n")
        f.write(" * N64Recomp does not emit prototypes into funcs.h.\n")
        f.write(" */\n")
        f.write("#ifndef BH_RECOMP_EXTRAS_H\n")
        f.write("#define BH_RECOMP_EXTRAS_H\n\n")
        f.write('#include "recomp.h"\n\n')
        f.write("#ifdef __cplusplus\n")
        f.write('extern "C" {\n')
        f.write("#endif\n\n")
        for name in missing:
            f.write(f"void {name}(uint8_t* rdram, recomp_context* ctx);\n")
        f.write("\n#ifdef __cplusplus\n")
        f.write("}\n")
        f.write("#endif\n\n")
        f.write("#endif\n")

    print(f"Wrote {len(missing)} extra declarations to {out_p}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
